# -*- coding: utf-8 -*-
"""Computational_complexity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qADCH56ZPc2Bvdv_JVOAZfnvogizQHn_
"""

import numpy as np
import random
l = list(range(100))
random.shuffle(l)
l

# search for an element q in the list : O(n) where n is the length of the list
q=31
isFound = False;
for ele in l:
  if ele==31:
    print("Found")
    isFound=True
    break;
if isFound == False:
  print("Not Found")

l1 = list(range(100))
random.shuffle(l1)
l2 = list(range(50))
random.shuffle(l2)
smallList={}
for ele in l2:
  smallList[ele] = 1

cnt = 0
for i in l1:
  if smallList.get(i):

    print(i)
    cnt +=1

print("number of common elements", cnt)

# find common elements in two lists
l1 = list(range(100))
random.shuffle(l1)

l2 = list(range(50))
random.shuffle(l2)

cnt =0
for i in l1:
  for j in l2:
    if i==j:
      print(i)
      cnt +=1
print("number of common elements", cnt)