# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UKvpIovdWLLtUJwCPthwvBKZB8dZw6ei
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
Iris = pd.read_csv("Iris.csv")
Iris

# print datapoints and features
print(Iris.shape)

# column name in dataset
print(Iris.columns)

# data points for each class which are present
# number of flowers for which each species are present
Iris["Species"].value_counts()

# scatter plot
Iris.plot(kind='scatter' , x='SepalLengthCm' , y='SepalWidthCm')
plt.show()

