# -*- coding: utf-8 -*-
"""Practice29March.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vikIlOf_3wicGVog29XArPy-ZZdRRE2u
"""

import pandas as pd
data = pd.read_csv('train.csv')
data

# no. of female passengers
female_passengers = data[data['Sex']== 'female']
print(len(female_passengers))

# number of females survived
female_survived = female_passengers[female_passengers['Survived']==1].shape[0]
print("Number of females survived :",female_survived)

# no. of male passengers
male_passengers = data[data['Sex']== 'male']
print(len(male_passengers))

# number of males survived
male_survived = male_passengers[male_passengers['Survived']==1].shape[0]
print("Number of males survived :",male_survived)

# bar graph
import matplotlib.pyplot as plt

survivors_by_gender = data.groupby(['Sex','Survived']).size().unstack()
survivors_by_gender.plot(kind='bar',stacked=True)

plt.title('Distribution of survivors by gender')
plt.xlabel('Gender')
plt.ylabel('Number of passengers')
plt.xticks(rotation = 0)
plt.legend(['Did not Survived','Survived'])

plt.show()

import seaborn as sns
survivors_by_gender = data.groupby(['Sex','Survived']).size().unstack()
sns.heatmap(survivors_by_gender, annot=True, fmt = 'd',cmap='YlGnBu')
plt.title('Distribution of Survivors by gender')
plt.xlabel('Survived')
plt.ylabel('gender')
plt.show()