# -*- coding: utf-8 -*-
"""Practice30March.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1isRubGHjOX4ncErw6vOHuWSZdxN_6aJM
"""

import pandas as pd
df = pd.read_csv('train.csv')
df

# Check for null values in the 'Cabin' column
null_cabin_values = df['Cabin'].isnull().sum()

print("Number of null values in the 'Cabin' column:", null_cabin_values)

# Drop the 'Cabin' column
df = df.drop(columns=['Cabin'])


print(df.head())   # to check

# Check for null values in the 'Ticket' column
null_ticket_values = df['Ticket'].isnull().sum()

print("Number of null values in the 'Ticket' column:", null_ticket_values)

# Calculating Family Groups
# Extract last names from the 'Name' column
df['Last Name'] = df['Name'].apply(lambda x: x.split(',')[0])

# Group passengers by last name and count the number of unique last names
unique_last_names = df['Last Name'].nunique()

# Group passengers by last name and count the number of unique last names with at least one survivor
family_groups_with_survivor = df[df['Survived'] == 1].groupby('Last Name').ngroups

print("Number of family groups with at least one survivor:", family_groups_with_survivor)
print("Total number of unique last names:", unique_last_names)

# Calculate the total number of siblings for each passenger
total_siblings = df['SibSp'].sum()

print("Total number of siblings:", total_siblings)