# -*- coding: utf-8 -*-
"""Practice26Mar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E07lf9i2P_yLUlikPP_mUpLLzhLGs5Cy
"""

import pandas as pd
df = pd.read_csv('train.csv')
df

# counting survivors
survived_count = df['Survived'].sum()
print(survived_count)

import matplotlib.pyplot as plt
survival_counts = df.groupby('Survived').size()

survival_counts.plot(kind='bar', title='Survivors vs Non-Survivors')
plt.xlabel('Survived')
plt.ylabel('Count')
plt.xticks([0,1],['No','Yes'])
plt.show()

survival_rate = df['Survived'].mean()

print("Total number of survivors: ", survived_count)

print("Survival rate: ", survival_rate)

import seaborn as sns
import matplotlib.pyplot as plt

# box plot
sns.boxplot(x='Pclass', y='Age', data=df)
plt.title('Age Distribution by Passenger Class')
plt.show()

# violin plot
sns.violinplot(x='Pclass', y='Age', data=df)
plt.title('Age Distribution by Passenger Class')
plt.show()



import seaborn as sns
import matplotlib.pyplot as plt
# Create age bins
age_bins = [0, 18, 30, 50, 100]
age_labels = ['0-18', '19-30', '31-50', '51+']
df['AgeGroup'] = pd.cut(df['Age'], bins=age_bins, labels=age_labels)

# bar plot of survival rates by age group
sns.barplot(x='AgeGroup', y='Survived', data=df, errorbar=None)
plt.title('Survival Rates by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Survival Rate')
plt.show()

# Create a bar plot of survival rates by passenger class
sns.barplot(x='Pclass', y='Survived', data=df, errorbar=None)
plt.title('Survival Rates by Passenger Class')
plt.xlabel('Passenger Class')
plt.ylabel('Survival Rate')
plt.show()



