# -*- coding: utf-8 -*-
"""Practice31March.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UA7h6vUoVjp4TqufYIPsIVYwhllq1XbG
"""

import pandas as pd
df = pd.read_csv('train.csv')
df
df.head(100)  # Display the first few rows