# -*- coding: utf-8 -*-
"""Practice25march.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bnYitZ34sQHChKxZe_H8xwh4lLWqiFuT
"""

import pandas as pd
df = pd.read_csv('train.csv')
df

Age_criteria =18

children = df[df['Age'] <= Age_criteria]

print(children)

# print number of children
number_of_children = len(children)
print(number_of_children)

# number of children survived
children_survived = df[(df['Age'] <=18) & (df['Survived'] == 1)]
print(len(children_survived))

youth_age_min = 19
youth_age_max = 39

youth = df[(df['Age'] >= youth_age_min) & (df['Age'] <= youth_age_max)]
number_of_youth = len(youth)
print(number_of_youth)

# number of youth survived
youth_survived = df[(df['Age'] >=19) &(df['Age'] <=39) & (df['Survived'] == 1)]
print(len(youth_survived))

middle_age_min =40
middle_age_max =60

middle_age_group = df[(df['Age'] >= middle_age_min) & (df['Age'] <=middle_age_max) ]
number_of_middle_group = len(middle_age_group)
print(number_of_middle_group)

# number of middle age people survived
middle_age_survived = df[(df['Age'] >=40) &(df['Age'] <=60) & (df['Survived'] == 1)]
print(len(middle_age_survived))

old_age_min = 61
old_age_max = 125

old_age_group = df[(df['Age'] >= old_age_min) & (df['Age'] <= old_age_max)]
number_of_old_group = len(old_age_group)
print(number_of_old_group)

# number of old age people survived
old_age_survived = df[(df['Age'] >=61) &(df['Age'] <=125) & (df['Survived'] == 1)]
print(len(old_age_survived))